#!/usr/bin/env python3
"""Split the master spec into docs/spec/ per §29.1. Use --check to verify the split is in sync."""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "Household_Hub_iOS_App_Specs_Enhanced_v3.1.md"
OUT = ROOT / "docs" / "spec"

# §0, §17 and §20-§23 are not assigned by §29.1; placement below is a documented judgment call.
FILES = [
    ("01-vision-and-scope.md", "Vision and scope", [1, 2], "Every phase (scope checks)"),
    ("02-architecture.md", "Executive decisions and architecture", [0, 3, 4, 5], "Phase 1 onward"),
    ("03-domain-and-money.md", "Domain, money, data model, accounting, dates", [6, 7, 8, 9, 10], "Phases 2, 4, 5, 7"),
    ("04-zero-cost-and-ai.md", "Zero-cost constraint and AI strategy", [11, 12], "Phase 0, Phase 8"),
    ("05-testing-and-ci.md", "Testing and CI", [13, 14], "Every phase (verification)"),
    ("06-claude-code-ops.md", "Claude Code operations, phase order, gates", [15, 16, 17, 18, 19, 20, 21, 22, 23, 28, 29], "Phase 0, every phase gate"),
    ("07-ux-and-screens.md", "UX, navigation, screens", [24], "Phases 3-6, 9"),
    ("08-parsing-and-backup.md", "Quick Add grammar and backup schema", [25, 26], "Phases 3, 7, 8"),
    ("09-nfrs.md", "Performance budgets", [27], "Phase 10, perf tests"),
]


def sections():
    lines = SOURCE.read_text(encoding="utf-8").splitlines(keepends=True)
    heads, in_fence = [], False
    for i, line in enumerate(lines):
        if line.startswith("```"):
            in_fence = not in_fence
        elif not in_fence:
            m = re.match(r"^# (\d+)\. (.+)$", line)
            if m:
                heads.append((i, int(m.group(1)), m.group(2).strip()))
    out = {}
    for n, (start, num, title) in enumerate(heads):
        end = heads[n + 1][0] if n + 1 < len(heads) else len(lines)
        body = "".join(lines[start:end]).rstrip()
        body = re.sub(r"\n+---\s*$", "", body)
        out[num] = (title, body + "\n")
    return out


def render():
    secs = sections()
    missing = sorted(set(secs) - {s for _, _, nums, _ in FILES for s in nums})
    if missing:
        sys.exit(f"split-spec: sections {missing} not assigned to any file")
    src = SOURCE.relative_to(ROOT)
    files = {}
    for name, title, nums, _ in FILES:
        parts = [
            f"<!-- GENERATED by Scripts/split-spec.py from {src}. Do not edit; edit the source and re-run. -->\n",
            f"# {title} (§{', §'.join(map(str, nums))})\n",
        ]
        parts += ["\n" + secs[n][1] for n in nums]
        files[name] = "".join(parts)
    idx = [
        f"<!-- GENERATED by Scripts/split-spec.py from {src}. Do not edit; edit the source and re-run. -->\n",
        "# Household Hub spec index\n\n",
        f"Source of truth: `{src}` (v3.1). These files are verbatim extracts for token-efficient loading (§29.2):\n",
        "read this index plus only the file(s) relevant to the task.\n\n",
        "| File | Sections | Needed by |\n|---|---|---|\n",
    ]
    for name, _, nums, need in FILES:
        titles = "; ".join(f"§{n} {secs[n][0]}" for n in nums)
        idx.append(f"| [{name}]({name}) | {titles} | {need} |\n")
    idx.append(
        "\nPlacement note: §29.1 does not assign §0, §17, §20-§23. §0 lives in 02 (architecture decisions);"
        " §17 and §20-§23 live in 06 (tooling, research changes, phase order, references, audit log).\n"
    )
    files["00-index.md"] = "".join(idx)
    return files


def main():
    files = render()
    if "--check" in sys.argv:
        stale = [n for n, c in files.items() if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != c]
        extra = [p.name for p in OUT.glob("*.md") if p.name not in files]
        if stale or extra:
            print(f"docs/spec is out of sync with {SOURCE.name}. Stale: {stale} Unexpected: {extra}")
            print("Fix: python3 Scripts/split-spec.py")
            sys.exit(1)
        print("docs/spec in sync")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (OUT / name).write_text(content, encoding="utf-8")
    print(f"wrote {len(files)} files to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
